### PR TITLE
Activate 'App Deletion' from GUI

### PR DESCRIPTION
**Pull request by rohitadeshmukh13**
Added code to invoke the API method 'wipe' on click of the delete button on app-cards

### CODE REVIEW

**Comment by JulianSchuette** [comment]
Thanks  a lot, looks good at a first glance. Could you fix the failed checks (sign off your commits to confirm the DCO and fix the linter complaints)?

**Comment by rohitadeshmukh13** [comment]
Thanks! I've fixed the linting errors and signed off all of my commits to confirm the DCO.

**Comment by JulianSchuette** [comment]
Just saw that this PR is against master. Latest version is in `develop` and it is way ahead of `master`.

Could you submit the PR against `develop` branch? Sorry, will add this hint to CONTRIBUTING.md

**Comment by JulianSchuette** [comment]
Set default branch to `develop`.

**Comment by rohitadeshmukh13** [comment]
Sure! I've now changed the base branch to 'develop'.

**Comment by oxisto** [comment]
Would it be possible to branch this again from the develop? I've tried to manually merge this but it doesn't look good :(

**Comment by rohitadeshmukh13** [comment]
Okay, sure! I'll close this PR and open another for that.

**Pull request closed without merging**
